### ISSUE TITLE
GitHub Actions für E2E Testing

### ISSUE THREAD

**Issue by robinboehm** [coding-bootcamps-eu/ama-tool#22]
- [x] GitHub Actions einlesen
- [x] GitHub Action für E2E Cypress erstellen
- [x] GitHub Action für Discord Nachricht bei dev merge erstellen
- [x] Lighting Talk für GitHub Actions (15min + 15min Q/A)

**Comment by glissario** [comment]
Actions are triggered - waiting for merged e2e-tests

**Comment by glissario** [comment]
Three tests are running completely - e2e is commented out because of missing functionality
