### ISSUE TITLE
Listen-Ansicht erstellt

### ISSUE THREAD

**Issue by robinboehm** [coding-bootcamps-eu/ama-tool#5]
Als Teilnehmer:in möchte alle Fragen die gestellt wurden und noch nicht beantwortet sind in einer Liste sehen.

- [x] Liste der Fragen sehen (Title + Kategorie, Status)
- [x] Filterung. Default-> alle offenen oder alle archivierte anzeigen
- [x] Sortierung nach Upvotes in Liste (Absteigend)
- [x] Button pro Listeneintrag der ein Upvote per Frage ermöglicht (Max 1x pro Frage/Browser)
- [x] Voting kann zurückgezogen werden
- [x] Status von offen auf erledigt gewechselt werden
- [x] User ID generierung
- [x] Filterung der Listen in einer
- [x] Layout aus Figma Design ist umgesetzt
- [x] A11y Rules gecheckt

Status: Offen, Archiviert

**Comment by ChristianMLux** [comment]
Layout aus Figma nicht aktuell. Warten diesbezüglich auf neuen Input.
