### ISSUE TITLE
Datentyp für AMA-Eintrag ist definiert

### ISSUE THREAD

**Issue by robinboehm** [coding-bootcamps-eu/ama-tool#8]
Als Entwickler:innen benötigen wir ein gemeinsamen DatenTyp um unsere Daten innerhalb der Anwendung zu verwalten.

Folgende Felder sollten mindestens enthalten sein:
- id
- title
- description
- category
- isDone
- created_at

**Comment by glissario** [comment]
suggested datatype:

```json 
[
  {
    "id": 1,
    "title": "First entry",
    "description": "Initialisation of data type",
    "category": "Allgemein",
    "isDone": false,
    "created_at": "Tue Aug 19 1975 23:15:30 GMT+0200 (CEST)",
    "author": "Christian",
    "upvotes": 0
  }
]
```

"created_at" -> (new Date()).toString()

**Comment by robinboehm** [comment]
`created_at`sollte should be an ISO String that is parsable

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse
